# Numpy

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

arr = np.random.uniform(0, 20, size=(4,7))
arr

array([[1.86012534e+01, 7.64112831e+00, 1.87735279e+01, 1.75189757e+01,
        1.07541079e+01, 1.05191115e-02, 1.72540117e+01],
       [4.38812655e+00, 1.33310487e+01, 3.85359828e+00, 1.30703194e+01,
        6.11027908e+00, 6.92771947e+00, 3.53883486e+00],
       [1.84153407e+01, 3.64136325e+00, 1.68581030e+01, 1.85817798e+01,
        1.55724473e+00, 5.75467576e+00, 1.90066664e+00],
       [1.71154724e+00, 1.28249428e+01, 1.53421666e+01, 1.61865436e+01,
        5.70418842e+00, 7.52776682e+00, 9.36661647e+00]])

Это означает, что для каждого элемента массива нужно выполнить преобразование вида ax + b, где a и b - это некоторые числа, а x - это исходное значение элемента массива. Цель такого преобразования - привести значения массива к определенному диапазону или масштабу.
```
Нормализация - это метод масштабирования, при котором значения смещаются и масштабируются таким образом, чтобы в конечном итоге они оказались в диапазоне от 0 до 1. Это также известно как масштабирование минимум-максимум.
```
Формула нормализации: $X’ = (X - X_{min}) / (X_{max} - X_{min}).$ \
Здесь $X_{max}$ и $X_{min}$ - максимальное и минимальное значения признака соответственно.


In [2]:
arr_normalize = (arr - arr.min()) / (arr.max() - arr.min())
arr_normalize

array([[0.9908184 , 0.40668367, 1.        , 0.93313694, 0.57259413,
        0.        , 0.91901532],
       [0.23331053, 0.70993569, 0.20482212, 0.69603977, 0.32509498,
        0.36866157, 0.18804637],
       [0.98090993, 0.19351076, 0.89791483, 0.98978053, 0.08243484,
        0.30614262, 0.10073798],
       [0.0906586 , 0.68296209, 0.81712095, 0.86212317, 0.30345183,
        0.40064191, 0.4986459 ]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

$√(Σ(xi-yi)²)$

In [3]:
arr1, arr2 = (np.random.randint(0, 10, size=10) for i in range(2))
evklid = np.sqrt(((arr1 - arr2)**2).sum())
evklid

16.24807680927192

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [51]:
A, B, C = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]), np.array([[3, -1], [2, 1]]), np.array([[7, 21], [11, 8], [8, 4]])

A_1, B_1 = np.linalg.inv(A), np.linalg.inv(B)

X = A_1 @ (-C) @ B_1
X                                                                     

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [52]:
d = np.loadtxt('../data sources/minutes_n_ingredients.csv', dtype = np.int32, delimiter = ',', skiprows = 1)
d[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [53]:
data = np.loadtxt('../data sources/minutes_n_ingredients.csv', dtype = np.int32, delimiter = ',', skiprows = 1, usecols=(1,2))
first, second = ((data[:, i].mean(), data[:, i].min(), data[:, i].max(), np.median(data, axis=0)[i]) for i in range(2))
[print(f"Столбец:\n{'Среднее =':>15} {col[0]}\n{'Минимальное =':>15} {col[1]}\n{'Максимальное =':>15} {col[2]}\n{'Медиана =':>15} {col[3]}\n\n\n") for col in [first, second]]

Столбец:
      Среднее = 21601.00169
  Минимальное = 0
 Максимальное = 2147483647
      Медиана = 40.0



Столбец:
      Среднее = 9.05528
  Минимальное = 1
 Максимальное = 39
      Медиана = 9.0





[None, None]

In [54]:
print(f"1 Столбец:\n{'Среднее =':>15} {first[0]}\n{'Минимальное =':>15} {first[1]}\n{'Максимальное =':>15} {first[2]}\n{'Медиана =':>15} {first[3]}\n\n\n")
print(f"2 Столбец:\n{'Среднее =':>15} {second[0]}\n{'Минимальное =':>15} {second[1]}\n{'Максимальное =':>15} {second[2]}\n{'Медиана =':>15} {second[3]}")

1 Столбец:
      Среднее = 21601.00169
  Минимальное = 0
 Максимальное = 2147483647
      Медиана = 40.0



2 Столбец:
      Среднее = 9.05528
  Минимальное = 1
 Максимальное = 39
      Медиана = 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [55]:
minutes = np.loadtxt('../data sources/minutes_n_ingredients.csv', dtype = np.int32, delimiter = ',', skiprows = 1, usecols=1)
limit = np.quantile(minutes, 0.75)
d[minutes < limit]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [371794,     35,      8],
       [ 43407,     35,      7],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [56]:
print(f"Количество рецептов у которых продолжительность равна нулю - {len(minutes[minutes == 0])}")

Количество рецептов у которых продолжительность равна нулю - 479


In [57]:
minutes[minutes == 0 ] = 1
print(f"Количество рецептов у которых продолжительность равна нулю - {len(minutes[minutes == 0])}")

Количество рецептов у которых продолжительность равна нулю - 0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [59]:
data = np.loadtxt('../data sources/minutes_n_ingredients.csv', dtype = np.int32, delimiter = ',', skiprows = 1)
print(f"Количество уникальных рецептов - {len(np.unique(data))}")

Количество уникальных рецептов - 100545


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [61]:
n_ingredients = np.loadtxt('../data sources/minutes_n_ingredients.csv', dtype = np.int32, delimiter = ',', skiprows = 1, usecols=2)
print(f"Количество уникальных значений = {len(np.unique(n_ingredients))}")
print(np.unique(n_ingredients))

Количество уникальных значений = 37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [62]:
d[n_ingredients <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [63]:
average_v = n_ingredients / minutes
print(average_v.max())

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [64]:
top_100 = d[d[:, 2].argsort()[:-101:-1]]
top_100[:, 1].mean()

227.87

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [65]:
np.random.permutation(d)[:10]

array([[502890,    140,      9],
       [444839,     60,     10],
       [ 93690,     10,      6],
       [ 49542,     25,     10],
       [497159,     33,      8],
       [108652,     15,      7],
       [396927,     30,      8],
       [305507,     60,     10],
       [ 84078,     65,     13],
       [ 50730,     65,     10]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [68]:
d = np.loadtxt('../data sources/minutes_n_ingredients.csv', dtype = np.int32, delimiter = ',', skiprows = 1)
average_ingredients = d[:, 2].mean()
average_ingredients
print(f"{round(len(d[d[:, 2] < average_ingredients]) * 100 / len(d), 1)}% рецептов в датасете у которых количество ингридиентов меньше среднего.")


58.8% рецептов в датасете у которых количество ингридиентов меньше среднего.


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [71]:
"""
Метод Numpy c_ используется для перевода объектов среза в конкатенацию вдоль второй оси. 
Он используется для соединения двух матриц по строкам.
"""

mask = (n_ingredients <= 5) & (minutes <= 20)
new_d = np.c_[d, mask]
new_d

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [72]:
print(f"{round(len(new_d[new_d[:, 3] == 1])/len(new_d[:, 3]) * 100, 2)}%")

9.55%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [73]:
short = d[d[:,1] < 10]
standard = d[(d[:,1] >= 10) & (d[:,1] < 20)]
long = d[20 <= d[:,1]]

max_value = np.min([short.shape[0], standard.shape[0], long.shape[0]])

result = np.array([short[:max_value], standard[:max_value], long[:max_value]])
print(result)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      0      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
